services:
  - type: worker
    name: smartmate-bot
    env: python
    buildCommand: pip install -r render_requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 1